### ISSUE TITLE
there are lots of bugs in website and also lots of flows in doc i will love to collaborate in it 

### ISSUE THREAD

**Issue by madilraza** [NextGenSoftwareUK/Our-World-OASIS-API-HoloNET-HoloUnity-And-.NET-HDK#1]

**Comment by dellams** [comment]
Hi, sorry didn't see your message till now, not use to having to check the issues section for messages... your the first one so congratulations! :)

Which project are you referring to with the bugs? Thanks.

Lots of flows in doc? Sorry not sure what you mean by that? :)

Yes, would be great to collaborate, what is your background? How can you help?

Cheers
D.
